статистика
Ruslan-Bulatovich/java-explore-with-me pull request #5
Opened 2023-06-10 12:29 UTC by Ruslan-Bulatovich

2023-06-10 21:17 UTC, alexache requested changes

2023-06-10 21:17 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/client/event/statclient/StatisticClient.java
> +    public void postStats(HttpServletRequest servlet, String app) {
Лучше бы не полагаться на HttpServletRequest, а получать конкретные аргументы

2023-06-10 21:17 UTC, alexache commented on stats/stats-server/pom.xml
> +            <version>1.5.3.Final</version>
Версии зависимостей должны быть указаны только в родительском модуле

2023-06-10 21:17 UTC, alexache commented on stats/stats-server/pom.xml
> +                <version>3.8.1</version>
Как и версии плагинов - только в родительском модуле

2023-06-10 21:17 UTC, alexache commented on stats/stats-server/pom.xml
> +                            <version>1.18.24</version>
И опять же версии библиотек - только в родительском модуле

2023-06-10 21:17 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/server/controller/StatisticController.java
> +    public ResponseEntity<ResponseEndpointHitDto> addEndpointHit(@RequestBody CreateEndpointHitDto endpointHitDto) {
Мне кажется, не хватает аннотации @Valid

2023-06-11 14:06 UTC, Ruslan-Bulatovich commented on stats/stats-server/src/main/java/ru/practicum/server/controller/StatisticController.java
> +    public ResponseEntity<ResponseEndpointHitDto> addEndpointHit(@RequestBody CreateEndpointHitDto endpointHitDto) {
исправил

2023-06-11 14:07 UTC, Ruslan-Bulatovich commented on stats/stats-server/pom.xml
> +                            <version>1.18.24</version>
исправил

2023-06-11 14:07 UTC, Ruslan-Bulatovich commented on stats/stats-server/pom.xml
> +                <version>3.8.1</version>
исправил

2023-06-11 14:07 UTC, Ruslan-Bulatovich commented on stats/stats-server/pom.xml
> +            <version>1.5.3.Final</version>
исправил

2023-06-11 14:07 UTC, Ruslan-Bulatovich commented on stats/stats-client/src/main/java/ru/practicum/client/event/statclient/StatisticClient.java
> +    public void postStats(HttpServletRequest servlet, String app) {
исправил

2023-06-11 14:07 UTC, Ruslan-Bulatovich commented
Привет! Я все исправил, надеюсь зависимости в  pom файлах теперь верны

2023-06-11 20:38 UTC, alexache approved these changes

2023-06-13 09:21 UTC, merged