Основной сервис
Ruslan-Bulatovich/java-explore-with-me pull request #7
Opened 2023-06-17 17:00 UTC by Ruslan-Bulatovich

2023-06-19 17:54 UTC, Ruslan-Bulatovich commented
Привет! Основной серис готов. Я убрал последним коммитом лишнее, а именно фича комментов. Пока это у меня не работает, да и тесты еще дописал. Только сегодня узнал, что это третий этап)

2023-06-19 21:23 UTC, alexache requested changes

2023-06-19 21:23 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + requestsToUpdate.size());
Так не надо делать

2023-06-19 21:23 UTC, alexache commented on main_svc/src/main/resources/schema.sql
> +    confirmed_Requests bigint,
Не должно быть такого столбца - это дублирования информации из таблицы заявок

2023-06-19 21:23 UTC, alexache commented on main_svc/src/main/resources/schema.sql
> +    views              bigint,
Как и это не должно храниться в базе

2023-06-19 21:23 UTC, alexache commented on main_svc/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS comments
Еще немного рано :) (будет сложнее проверять следующий этап, если оставить)

2023-06-19 21:23 UTC, alexache commented on stat_svc/stat_client/pom.xml
> +            <version>2.14.1</version>
Не должно быть версий

2023-06-19 21:23 UTC, alexache commented on stat_svc/stat_server/pom.xml
> +            <version>2.7.4</version>
Не должно быть версий библиотек

2023-06-19 21:23 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        setView(events);
Интересно, просмотры выставляются после сортировки по количеству просмотров

2023-06-19 21:23 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +    private void sendStatForTheEvent(Long eventId, String remoteAddr, LocalDateTime now,
Приватные методы должны быть после публичных методов

2023-06-19 21:23 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        sendStatForEveryEvent(events, remoteAddr, LocalDateTime.now(), nameService);
Выглядит чем-то немного лишним, еще и с запросами к сервису в цикле

2023-06-23 20:35 UTC, Ruslan-Bulatovich commented on docker-compose.yml
> +      - ewm-db
исправил

2023-06-23 20:35 UTC, Ruslan-Bulatovich commented on main_svc/pom.xml
> +            <version>42.3.8</version>
Исправил

2023-06-23 20:35 UTC, Ruslan-Bulatovich commented on main_svc/pom.xml
> +            <version>1.5.3.Final</version>
исправил

2023-06-23 20:36 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/MainServiceApplication.java
> +    @Bean
Не исправил

2023-06-23 20:36 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/controllers/admin/AdminEventController.java
> +                                        @RequestParam(name = "from", required = false, defaultValue = "0") Integer from,
Добавил аннотации для времени старта и конца

2023-06-23 20:37 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/controllers/pub/PublicEventController.java
> +        return eventService.getEventsWithParamsByUser(text, categories, paid, rangeStart, rangeEnd, onlyAvailable, sort, from, size, request);
исправил

2023-06-23 20:37 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/dto/event/EventFullDto.java
> +    private Location location;
Это ж дто. Отдельно есть модель Event

2023-06-23 20:37 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/dto/event/EventFullDto.java
> +    private Integer confirmedRequests;
Исправил

2023-06-23 20:38 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/models/Event.java
> +    private int confirmedRequests;
исправил, точно, абсолютно лишнее

2023-06-23 20:38 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/models/Event.java
> +    private Long views;
исправил

2023-06-23 20:40 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/models/Request.java
> +    private Long event;
я подумал, что не стоит в  запросе держать другую модель. Независимость пусть будет. Если надо доп информацию с помощью Join получим более полную информацию

2023-06-23 20:40 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/repositories/RequestRepository.java
> +    @Query("select p from Request as p " +
Ты прав, но лучше  у меня не получилось

2023-06-23 20:40 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/CategoryServiceImpl.java
> +        /*if(categoryDto.getName().equals(category.getName())) {
убрал

2023-06-23 20:41 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/CategoryServiceImpl.java
> +            System.out.println("Не ок");
Убрал

2023-06-23 20:44 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/CompilationServiceImpl.java
> +        compilation.setEvents(new HashSet<>(events));
Если не переопределен хешкод, то будет  разный хешкод для объектов с одинаковыми полями и  может такое произойти, что сет сохранит соответственно одинаковые объекты

2023-06-23 20:49 UTC, Ruslan-Bulatovich commented
Привет, спасибо за ценные замечания,я поправил почти все. Некоторые исправления мне дались сложно=/
P.S  Прошу не ссуди строго, могу на 3 этапе, если что поправить:)

2023-06-23 20:52 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        if (event.getPublishedOn() == null) {
исправил

2023-06-23 20:53 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        List<Request> requests = requestRepository.findAllByEvent(eventId);
Поправил, добавил новый метод  репозитория

2023-06-23 20:53 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +            return result;
добавил

2023-06-23 20:53 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + requestsToUpdate.size());
Исправил, оказалось вообще лишним

2023-06-23 20:53 UTC, Ruslan-Bulatovich commented on main_svc/src/main/resources/schema.sql
> +    confirmed_Requests bigint,
удалил

2023-06-23 20:53 UTC, Ruslan-Bulatovich commented on main_svc/src/main/resources/schema.sql
> +    views              bigint,
удалил

2023-06-23 20:54 UTC, Ruslan-Bulatovich commented on main_svc/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS comments
убрал

2023-06-23 20:54 UTC, Ruslan-Bulatovich commented on stat_svc/stat_client/pom.xml
> +            <version>2.14.1</version>
убрал

2023-06-23 20:54 UTC, Ruslan-Bulatovich commented on stat_svc/stat_server/pom.xml
> +            <version>2.7.4</version>
убрал

2023-06-23 20:54 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +    private void sendStatForTheEvent(Long eventId, String remoteAddr, LocalDateTime now,
убрал

2023-06-23 20:54 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        sendStatForEveryEvent(events, remoteAddr, LocalDateTime.now(), nameService);
я не придумал как лучше

2023-06-23 20:56 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        setView(events);
Я подумал, что пусть отсортирует, то что было, а со следующим запросом уже добавится прошлый просмотр. Не думаю, что это критично

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/controllers/admin/AdminEventController.java
> +                                        @RequestParam(name = "from", required = false, defaultValue = "0") Integer from,
Я и про from / size

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/dto/event/EventFullDto.java
> +    private Location location;
Я про Location

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        Integer confirmedRequests = requestRepository.findRequestByEventAndStatus(event.getId(), RequestStatus.CONFIRMED).size();
(опционально) еще можно использовать не find* метод, а count*

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        if (getConfirmedRequests(event) + requestsToUpdate.size() > event.getParticipantLimit() && requestStatusUpdateDto.getStatus().equals(RequestStatusToUpdate.CONFIRMED)) {
Можно делать гибче - подтверждать некоторое количество заявок, пока лимит не будет достигнут, и только потом реджектить

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +    private Integer getConfirmedRequests(Event event) {
Метод не выглядит очень полезным

2023-06-24 08:29 UTC, alexache commented on stat_svc/pom.xml
> +    <dependencyManagement>
Это должно быть в родительском модуле

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/models/Request.java
> +    private Long event;
Тогда не получатся богатые запросы в репозитории по join таблицам

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/repositories/RequestRepository.java
> +    @Query("select p from Request as p " +
Так о том я говорю в другом комментарии - нужно иметь User и Event в модели

2023-06-24 08:29 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        setView(events);
просмотры не хранятся в таблице, а значит равны нулю, тогда сортировка вообще не работает

2023-06-24 08:38 UTC, alexache requested changes

2023-06-24 08:38 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +                    .filter((event -> requestRepository.findRequestByEventAndStatus(event.getId(), RequestStatus.CONFIRMED).size() < (long) event.getParticipantLimit()))
Запросы к базе в цикле запрещены

2023-06-24 08:38 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        eventFullDtoList = events.stream().map(this::setConfirmedRequest).collect(Collectors.toList());
Запросы к базе в цикле запрещены

2023-06-24 08:38 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        sendStatForEveryEvent(events, remoteAddr, LocalDateTime.now(), nameService);
Мне кажется, что это просто лишнее

2023-06-24 08:38 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +                    .filter((event -> requestRepository.findRequestByEventAndStatus(event.getId(), RequestStatus.CONFIRMED).size() < (long) event.getParticipantLimit()))
Можно сначала получить данные о количестве заявок, а потом уже фильтровать на основе этих данных

2023-06-24 08:46 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        Integer confirmedRequests = requestRepository.findRequestByEventAndStatus(event.getId(), RequestStatus.CONFIRMED).size();
не могу откомментировать первые два замечания, но "Я и про from / size" и "Я про Location" можно чуточку понятнее выделять в пером ревью, не всегда понятно:)

2023-06-24 09:02 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        Integer confirmedRequests = requestRepository.findRequestByEventAndStatus(event.getId(), RequestStatus.CONFIRMED).size();
У меня показывает правильно - именно на ту строку с Location и from/size, странно

2023-06-25 15:46 UTC, Ruslan-Bulatovich commented
Привет. После того как убрал запросы в цикле, кажется и тесты быстрее проходили)

2023-06-25 15:47 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        eventFullDtoList = events.stream().map(this::setConfirmedRequest).collect(Collectors.toList());
убрал

2023-06-25 15:47 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +                    .filter((event -> requestRepository.findRequestByEventAndStatus(event.getId(), RequestStatus.CONFIRMED).size() < (long) event.getParticipantLimit()))
убрал

2023-06-25 15:48 UTC, Ruslan-Bulatovich commented on stat_svc/pom.xml
> +    <dependencyManagement>
исправил

2023-06-25 15:48 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +    private Integer getConfirmedRequests(Event event) {
согласен, убрал

2023-06-25 15:48 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        if (getConfirmedRequests(event) + requestsToUpdate.size() > event.getParticipantLimit() && requestStatusUpdateDto.getStatus().equals(RequestStatusToUpdate.CONFIRMED)) {
Не стал менять,  может и выглядит монструозно, но работает, может что нибудь и придумаю

2023-06-25 15:50 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +        Integer confirmedRequests = requestRepository.findRequestByEventAndStatus(event.getId(), RequestStatus.CONFIRMED).size();
Да, сам ошибся, столько правок и не заметил. И прошу, потому что я к сожалению не всегда понимаю, задаешь ли ты вопрос или просишь внести изменения)

2023-06-25 18:15 UTC, alexache approved these changes

2023-06-25 18:15 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/models/Request.java
> +    Event event;
Не хватает модификатора доступа поля

2023-06-25 18:15 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/RequestServiceImpl.java
> +    List<Request> getParticipationRequests(Long userId, Long eventId) {
Не хватает модификатора доступа поля

2023-06-25 18:42 UTC, merged