Feature comments
Ruslan-Bulatovich/java-explore-with-me pull request #8
Opened 2023-06-25 18:42 UTC by Ruslan-Bulatovich

2023-06-27 07:28 UTC, alexache requested changes

2023-06-27 07:28 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/dto/comment/CommentDto.java
> +    private String text;
Может добавить чуть больше валидаций?

2023-06-27 07:28 UTC, alexache commented on main_svc/src/main/java/ru/practicum/main/services/impl/CommentServiceImpl.java
> +
Можно докрутить такой флоу, что комментарий может оставлять только пользователь, который посещал событие (проверить табличку с подтвержденными заявками)

2023-06-29 06:19 UTC, Ruslan-Bulatovich commented on main_svc/src/main/java/ru/practicum/main/dto/comment/CommentDto.java
> +    private String text;
добавил

2023-06-29 06:21 UTC, Ruslan-Bulatovich commented
Привет! Спасибо за ревью! Классная идея проверки создания комментарий . Пока оставлю как есть)

2023-06-29 19:44 UTC, alexache approved these changes

2023-07-06 17:05 UTC, merged